# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Regional modelling with Anemoi
email: thomasn@met.no
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/anemoi-regional-tutorial" # the subpath of your site, e.g. /blog
url: "https://metno.github.io/" # the base hostname & protocol for your site
github_username:  tnipen

# Build settings
markdown: kramdown
  # plugins:
  #   - jekyll-toc
  # toc:
  #   min_level: 1
  #   max_level: 3
  #   list_class: toc
  #   list_class: toc__list
  #   sublist_class: toc__sublist
