defaults:
  - data: zarr
  - dataloader: default
  - model: graphtransformer
  - training: default
  - graphs: stretched_grid
  - diagnostics: eval_rollout
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

dataloader:
  num_workers:
    training: 1
    validation: 1
    test: 1
    predict: 1
  batch_size:
    training: 1
    validation: 1
    test: 1
    predict: 1

  dataset:
    cutout:
      - dataset: ${hardware.paths.data}/${hardware.files.dataset_lam} #/lustre/storeB/project/nwp/aifs/havardhh/testing/zarr/${hardware.files.dataset_lam} #${hardware.paths.data}/${hardware.files.dataset_lam}
      - dataset: ${hardware.paths.data}/${hardware.files.dataset}
    adjust: all

  limit_batches:
    training: null #10
    validation: null #10
  training:
    start: 1979-01-01
    end: 2021-12-31 #15
    drop: [sdor, slor, cp, u_600, v_600, z_600, t_600, q_600, w_600]
    statistics: ${hardware.paths.data}/aifs-od-an-oper-0001-mars-n320-2019-2023-6h-v6.zarr
    sort_vars: True

  validation:
    start: 2022-01-01
    end: 2022-12-31
    drop: [sdor, slor, cp, u_600, v_600, z_600, t_600, q_600, w_600]
    statistics: ${hardware.paths.data}/aifs-od-an-oper-0001-mars-n320-2019-2023-6h-v6.zarr
    sort_vars: True

  test:
    start: 2022-01-01
    end: 2022-12-31
    drop: [sdor, slor, cp, u_600, v_600, z_600, t_600, q_600, w_600]
    statistics: ${hardware.paths.data}/aifs-od-an-oper-0001-mars-n320-2019-2023-6h-v6.zarr
    sort_vars: True

hardware:
  num_gpus_per_node: 1
  num_nodes: 1
  num_gpus_per_model: 1
  paths:
    data: /lustre/storeB/project/nwp/aifs/datasets/
    output: /lustre/storeB/project/nwp/aifs/test_output/
    graph: graphs/
  files:
    dataset: aifs-od-an-oper-0001-mars-o96-2016-2023-6h-v6.zarr #aifs-od-an-oper-0001-mars-o96-2016-2023-6h-v6.zarr
    graph: graph_mappings_o96_icosahedral_h_5.pt

diagnostics:
  log:
    mlflow:
      enabled: False
      offline: False
      experiment_name: 'metno'
      run_name: graphtr-512c_o96-pre-train
  plot:
    enabled: False
  print_memory_summary: True

graphs:
  save_graph_plots: False
  clobber: False

data:
  resolution: o96

model:
  num_channels: 512
  trainable_parameters:
    data: 0
    hidden: 0
    data2hidden: 0
    hidden2data: 0
    hidden2hidden: 0 # GNN and GraphTransformer Processor only

training:
  max_epochs: 200
  lr:
    iterations: 200000
